export * from './branch-office.schema';
export * from './address.schema';
export * from './student.schema';
export * from './family-status.schema';
export * from './parent-family.schema';
export * from './relationship.schema';
export * from './student-family.schema';
export * from './emergency-contact.schema';
export * from '../../educational-center/persistence/schemas/educational-center.schema';